// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_features.proto

#ifndef PROTOBUF_image_5ffeatures_2eproto__INCLUDED
#define PROTOBUF_image_5ffeatures_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace androar {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_image_5ffeatures_2eproto();
void protobuf_AssignDesc_image_5ffeatures_2eproto();
void protobuf_ShutdownFile_image_5ffeatures_2eproto();

class GPSPosition;
class CompassPosition;
class LocalizationFeatures;
class ObjectBoundingBox;
class ObjectMetadata;
class DetectedObject;
class ImageContents;
class Image;

enum DetectedObject_DetectedObjectType {
  DetectedObject_DetectedObjectType_UNKNOWN = 1,
  DetectedObject_DetectedObjectType_BUILDING = 2,
  DetectedObject_DetectedObjectType_LAST_ELEMENT = 3
};
bool DetectedObject_DetectedObjectType_IsValid(int value);
const DetectedObject_DetectedObjectType DetectedObject_DetectedObjectType_DetectedObjectType_MIN = DetectedObject_DetectedObjectType_UNKNOWN;
const DetectedObject_DetectedObjectType DetectedObject_DetectedObjectType_DetectedObjectType_MAX = DetectedObject_DetectedObjectType_LAST_ELEMENT;
const int DetectedObject_DetectedObjectType_DetectedObjectType_ARRAYSIZE = DetectedObject_DetectedObjectType_DetectedObjectType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DetectedObject_DetectedObjectType_descriptor();
inline const ::std::string& DetectedObject_DetectedObjectType_Name(DetectedObject_DetectedObjectType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DetectedObject_DetectedObjectType_descriptor(), value);
}
inline bool DetectedObject_DetectedObjectType_Parse(
    const ::std::string& name, DetectedObject_DetectedObjectType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DetectedObject_DetectedObjectType>(
    DetectedObject_DetectedObjectType_descriptor(), name, value);
}
// ===================================================================

class GPSPosition : public ::google::protobuf::Message {
 public:
  GPSPosition();
  virtual ~GPSPosition();
  
  GPSPosition(const GPSPosition& from);
  
  inline GPSPosition& operator=(const GPSPosition& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GPSPosition& default_instance();
  
  void Swap(GPSPosition* other);
  
  // implements Message ----------------------------------------------
  
  GPSPosition* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GPSPosition& from);
  void MergeFrom(const GPSPosition& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required float latitude = 1;
  inline bool has_latitude() const;
  inline void clear_latitude();
  static const int kLatitudeFieldNumber = 1;
  inline float latitude() const;
  inline void set_latitude(float value);
  
  // required float longitude = 2;
  inline bool has_longitude() const;
  inline void clear_longitude();
  static const int kLongitudeFieldNumber = 2;
  inline float longitude() const;
  inline void set_longitude(float value);
  
  // @@protoc_insertion_point(class_scope:androar.GPSPosition)
 private:
  inline void set_has_latitude();
  inline void clear_has_latitude();
  inline void set_has_longitude();
  inline void clear_has_longitude();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float latitude_;
  float longitude_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_image_5ffeatures_2eproto();
  friend void protobuf_AssignDesc_image_5ffeatures_2eproto();
  friend void protobuf_ShutdownFile_image_5ffeatures_2eproto();
  
  void InitAsDefaultInstance();
  static GPSPosition* default_instance_;
};
// -------------------------------------------------------------------

class CompassPosition : public ::google::protobuf::Message {
 public:
  CompassPosition();
  virtual ~CompassPosition();
  
  CompassPosition(const CompassPosition& from);
  
  inline CompassPosition& operator=(const CompassPosition& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CompassPosition& default_instance();
  
  void Swap(CompassPosition* other);
  
  // implements Message ----------------------------------------------
  
  CompassPosition* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CompassPosition& from);
  void MergeFrom(const CompassPosition& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required float angle = 1;
  inline bool has_angle() const;
  inline void clear_angle();
  static const int kAngleFieldNumber = 1;
  inline float angle() const;
  inline void set_angle(float value);
  
  // @@protoc_insertion_point(class_scope:androar.CompassPosition)
 private:
  inline void set_has_angle();
  inline void clear_has_angle();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float angle_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_image_5ffeatures_2eproto();
  friend void protobuf_AssignDesc_image_5ffeatures_2eproto();
  friend void protobuf_ShutdownFile_image_5ffeatures_2eproto();
  
  void InitAsDefaultInstance();
  static CompassPosition* default_instance_;
};
// -------------------------------------------------------------------

class LocalizationFeatures : public ::google::protobuf::Message {
 public:
  LocalizationFeatures();
  virtual ~LocalizationFeatures();
  
  LocalizationFeatures(const LocalizationFeatures& from);
  
  inline LocalizationFeatures& operator=(const LocalizationFeatures& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const LocalizationFeatures& default_instance();
  
  void Swap(LocalizationFeatures* other);
  
  // implements Message ----------------------------------------------
  
  LocalizationFeatures* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LocalizationFeatures& from);
  void MergeFrom(const LocalizationFeatures& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .androar.GPSPosition gps_position = 1;
  inline bool has_gps_position() const;
  inline void clear_gps_position();
  static const int kGpsPositionFieldNumber = 1;
  inline const ::androar::GPSPosition& gps_position() const;
  inline ::androar::GPSPosition* mutable_gps_position();
  inline ::androar::GPSPosition* release_gps_position();
  
  // optional .androar.CompassPosition compass_position = 2;
  inline bool has_compass_position() const;
  inline void clear_compass_position();
  static const int kCompassPositionFieldNumber = 2;
  inline const ::androar::CompassPosition& compass_position() const;
  inline ::androar::CompassPosition* mutable_compass_position();
  inline ::androar::CompassPosition* release_compass_position();
  
  // @@protoc_insertion_point(class_scope:androar.LocalizationFeatures)
 private:
  inline void set_has_gps_position();
  inline void clear_has_gps_position();
  inline void set_has_compass_position();
  inline void clear_has_compass_position();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::androar::GPSPosition* gps_position_;
  ::androar::CompassPosition* compass_position_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_image_5ffeatures_2eproto();
  friend void protobuf_AssignDesc_image_5ffeatures_2eproto();
  friend void protobuf_ShutdownFile_image_5ffeatures_2eproto();
  
  void InitAsDefaultInstance();
  static LocalizationFeatures* default_instance_;
};
// -------------------------------------------------------------------

class ObjectBoundingBox : public ::google::protobuf::Message {
 public:
  ObjectBoundingBox();
  virtual ~ObjectBoundingBox();
  
  ObjectBoundingBox(const ObjectBoundingBox& from);
  
  inline ObjectBoundingBox& operator=(const ObjectBoundingBox& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectBoundingBox& default_instance();
  
  void Swap(ObjectBoundingBox* other);
  
  // implements Message ----------------------------------------------
  
  ObjectBoundingBox* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectBoundingBox& from);
  void MergeFrom(const ObjectBoundingBox& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 bottom = 1;
  inline bool has_bottom() const;
  inline void clear_bottom();
  static const int kBottomFieldNumber = 1;
  inline ::google::protobuf::int32 bottom() const;
  inline void set_bottom(::google::protobuf::int32 value);
  
  // required int32 top = 2;
  inline bool has_top() const;
  inline void clear_top();
  static const int kTopFieldNumber = 2;
  inline ::google::protobuf::int32 top() const;
  inline void set_top(::google::protobuf::int32 value);
  
  // required int32 left = 3;
  inline bool has_left() const;
  inline void clear_left();
  static const int kLeftFieldNumber = 3;
  inline ::google::protobuf::int32 left() const;
  inline void set_left(::google::protobuf::int32 value);
  
  // required int32 right = 4;
  inline bool has_right() const;
  inline void clear_right();
  static const int kRightFieldNumber = 4;
  inline ::google::protobuf::int32 right() const;
  inline void set_right(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:androar.ObjectBoundingBox)
 private:
  inline void set_has_bottom();
  inline void clear_has_bottom();
  inline void set_has_top();
  inline void clear_has_top();
  inline void set_has_left();
  inline void clear_has_left();
  inline void set_has_right();
  inline void clear_has_right();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 bottom_;
  ::google::protobuf::int32 top_;
  ::google::protobuf::int32 left_;
  ::google::protobuf::int32 right_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_image_5ffeatures_2eproto();
  friend void protobuf_AssignDesc_image_5ffeatures_2eproto();
  friend void protobuf_ShutdownFile_image_5ffeatures_2eproto();
  
  void InitAsDefaultInstance();
  static ObjectBoundingBox* default_instance_;
};
// -------------------------------------------------------------------

class ObjectMetadata : public ::google::protobuf::Message {
 public:
  ObjectMetadata();
  virtual ~ObjectMetadata();
  
  ObjectMetadata(const ObjectMetadata& from);
  
  inline ObjectMetadata& operator=(const ObjectMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectMetadata& default_instance();
  
  void Swap(ObjectMetadata* other);
  
  // implements Message ----------------------------------------------
  
  ObjectMetadata* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectMetadata& from);
  void MergeFrom(const ObjectMetadata& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // optional string description = 2;
  inline bool has_description() const;
  inline void clear_description();
  static const int kDescriptionFieldNumber = 2;
  inline const ::std::string& description() const;
  inline void set_description(const ::std::string& value);
  inline void set_description(const char* value);
  inline void set_description(const char* value, size_t size);
  inline ::std::string* mutable_description();
  inline ::std::string* release_description();
  
  // @@protoc_insertion_point(class_scope:androar.ObjectMetadata)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_description();
  inline void clear_has_description();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::std::string* description_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_image_5ffeatures_2eproto();
  friend void protobuf_AssignDesc_image_5ffeatures_2eproto();
  friend void protobuf_ShutdownFile_image_5ffeatures_2eproto();
  
  void InitAsDefaultInstance();
  static ObjectMetadata* default_instance_;
};
// -------------------------------------------------------------------

class DetectedObject : public ::google::protobuf::Message {
 public:
  DetectedObject();
  virtual ~DetectedObject();
  
  DetectedObject(const DetectedObject& from);
  
  inline DetectedObject& operator=(const DetectedObject& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DetectedObject& default_instance();
  
  void Swap(DetectedObject* other);
  
  // implements Message ----------------------------------------------
  
  DetectedObject* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DetectedObject& from);
  void MergeFrom(const DetectedObject& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef DetectedObject_DetectedObjectType DetectedObjectType;
  static const DetectedObjectType UNKNOWN = DetectedObject_DetectedObjectType_UNKNOWN;
  static const DetectedObjectType BUILDING = DetectedObject_DetectedObjectType_BUILDING;
  static const DetectedObjectType LAST_ELEMENT = DetectedObject_DetectedObjectType_LAST_ELEMENT;
  static inline bool DetectedObjectType_IsValid(int value) {
    return DetectedObject_DetectedObjectType_IsValid(value);
  }
  static const DetectedObjectType DetectedObjectType_MIN =
    DetectedObject_DetectedObjectType_DetectedObjectType_MIN;
  static const DetectedObjectType DetectedObjectType_MAX =
    DetectedObject_DetectedObjectType_DetectedObjectType_MAX;
  static const int DetectedObjectType_ARRAYSIZE =
    DetectedObject_DetectedObjectType_DetectedObjectType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  DetectedObjectType_descriptor() {
    return DetectedObject_DetectedObjectType_descriptor();
  }
  static inline const ::std::string& DetectedObjectType_Name(DetectedObjectType value) {
    return DetectedObject_DetectedObjectType_Name(value);
  }
  static inline bool DetectedObjectType_Parse(const ::std::string& name,
      DetectedObjectType* value) {
    return DetectedObject_DetectedObjectType_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required .androar.DetectedObject.DetectedObjectType object_type = 1;
  inline bool has_object_type() const;
  inline void clear_object_type();
  static const int kObjectTypeFieldNumber = 1;
  inline ::androar::DetectedObject_DetectedObjectType object_type() const;
  inline void set_object_type(::androar::DetectedObject_DetectedObjectType value);
  
  // required .androar.ObjectBoundingBox bounding_box = 2;
  inline bool has_bounding_box() const;
  inline void clear_bounding_box();
  static const int kBoundingBoxFieldNumber = 2;
  inline const ::androar::ObjectBoundingBox& bounding_box() const;
  inline ::androar::ObjectBoundingBox* mutable_bounding_box();
  inline ::androar::ObjectBoundingBox* release_bounding_box();
  
  // optional .androar.ObjectMetadata metadata = 3;
  inline bool has_metadata() const;
  inline void clear_metadata();
  static const int kMetadataFieldNumber = 3;
  inline const ::androar::ObjectMetadata& metadata() const;
  inline ::androar::ObjectMetadata* mutable_metadata();
  inline ::androar::ObjectMetadata* release_metadata();
  
  // required string id = 4;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 4;
  inline const ::std::string& id() const;
  inline void set_id(const ::std::string& value);
  inline void set_id(const char* value);
  inline void set_id(const char* value, size_t size);
  inline ::std::string* mutable_id();
  inline ::std::string* release_id();
  
  // optional int32 distance_to_viewer = 5;
  inline bool has_distance_to_viewer() const;
  inline void clear_distance_to_viewer();
  static const int kDistanceToViewerFieldNumber = 5;
  inline ::google::protobuf::int32 distance_to_viewer() const;
  inline void set_distance_to_viewer(::google::protobuf::int32 value);
  
  // optional int32 angle_to_viewer = 6;
  inline bool has_angle_to_viewer() const;
  inline void clear_angle_to_viewer();
  static const int kAngleToViewerFieldNumber = 6;
  inline ::google::protobuf::int32 angle_to_viewer() const;
  inline void set_angle_to_viewer(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:androar.DetectedObject)
 private:
  inline void set_has_object_type();
  inline void clear_has_object_type();
  inline void set_has_bounding_box();
  inline void clear_has_bounding_box();
  inline void set_has_metadata();
  inline void clear_has_metadata();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_distance_to_viewer();
  inline void clear_has_distance_to_viewer();
  inline void set_has_angle_to_viewer();
  inline void clear_has_angle_to_viewer();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::androar::ObjectBoundingBox* bounding_box_;
  ::androar::ObjectMetadata* metadata_;
  int object_type_;
  ::google::protobuf::int32 distance_to_viewer_;
  ::std::string* id_;
  ::google::protobuf::int32 angle_to_viewer_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void  protobuf_AddDesc_image_5ffeatures_2eproto();
  friend void protobuf_AssignDesc_image_5ffeatures_2eproto();
  friend void protobuf_ShutdownFile_image_5ffeatures_2eproto();
  
  void InitAsDefaultInstance();
  static DetectedObject* default_instance_;
};
// -------------------------------------------------------------------

class ImageContents : public ::google::protobuf::Message {
 public:
  ImageContents();
  virtual ~ImageContents();
  
  ImageContents(const ImageContents& from);
  
  inline ImageContents& operator=(const ImageContents& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ImageContents& default_instance();
  
  void Swap(ImageContents* other);
  
  // implements Message ----------------------------------------------
  
  ImageContents* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ImageContents& from);
  void MergeFrom(const ImageContents& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string image_hash = 1;
  inline bool has_image_hash() const;
  inline void clear_image_hash();
  static const int kImageHashFieldNumber = 1;
  inline const ::std::string& image_hash() const;
  inline void set_image_hash(const ::std::string& value);
  inline void set_image_hash(const char* value);
  inline void set_image_hash(const char* value, size_t size);
  inline ::std::string* mutable_image_hash();
  inline ::std::string* release_image_hash();
  
  // required bytes image_contents = 2;
  inline bool has_image_contents() const;
  inline void clear_image_contents();
  static const int kImageContentsFieldNumber = 2;
  inline const ::std::string& image_contents() const;
  inline void set_image_contents(const ::std::string& value);
  inline void set_image_contents(const char* value);
  inline void set_image_contents(const void* value, size_t size);
  inline ::std::string* mutable_image_contents();
  inline ::std::string* release_image_contents();
  
  // @@protoc_insertion_point(class_scope:androar.ImageContents)
 private:
  inline void set_has_image_hash();
  inline void clear_has_image_hash();
  inline void set_has_image_contents();
  inline void clear_has_image_contents();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* image_hash_;
  ::std::string* image_contents_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_image_5ffeatures_2eproto();
  friend void protobuf_AssignDesc_image_5ffeatures_2eproto();
  friend void protobuf_ShutdownFile_image_5ffeatures_2eproto();
  
  void InitAsDefaultInstance();
  static ImageContents* default_instance_;
};
// -------------------------------------------------------------------

class Image : public ::google::protobuf::Message {
 public:
  Image();
  virtual ~Image();
  
  Image(const Image& from);
  
  inline Image& operator=(const Image& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Image& default_instance();
  
  void Swap(Image* other);
  
  // implements Message ----------------------------------------------
  
  Image* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Image& from);
  void MergeFrom(const Image& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .androar.ImageContents image = 1;
  inline bool has_image() const;
  inline void clear_image();
  static const int kImageFieldNumber = 1;
  inline const ::androar::ImageContents& image() const;
  inline ::androar::ImageContents* mutable_image();
  inline ::androar::ImageContents* release_image();
  
  // optional .androar.LocalizationFeatures localization_features = 2;
  inline bool has_localization_features() const;
  inline void clear_localization_features();
  static const int kLocalizationFeaturesFieldNumber = 2;
  inline const ::androar::LocalizationFeatures& localization_features() const;
  inline ::androar::LocalizationFeatures* mutable_localization_features();
  inline ::androar::LocalizationFeatures* release_localization_features();
  
  // repeated .androar.DetectedObject detected_objects = 3;
  inline int detected_objects_size() const;
  inline void clear_detected_objects();
  static const int kDetectedObjectsFieldNumber = 3;
  inline const ::androar::DetectedObject& detected_objects(int index) const;
  inline ::androar::DetectedObject* mutable_detected_objects(int index);
  inline ::androar::DetectedObject* add_detected_objects();
  inline const ::google::protobuf::RepeatedPtrField< ::androar::DetectedObject >&
      detected_objects() const;
  inline ::google::protobuf::RepeatedPtrField< ::androar::DetectedObject >*
      mutable_detected_objects();
  
  // repeated string possible_present_objects = 4;
  inline int possible_present_objects_size() const;
  inline void clear_possible_present_objects();
  static const int kPossiblePresentObjectsFieldNumber = 4;
  inline const ::std::string& possible_present_objects(int index) const;
  inline ::std::string* mutable_possible_present_objects(int index);
  inline void set_possible_present_objects(int index, const ::std::string& value);
  inline void set_possible_present_objects(int index, const char* value);
  inline void set_possible_present_objects(int index, const char* value, size_t size);
  inline ::std::string* add_possible_present_objects();
  inline void add_possible_present_objects(const ::std::string& value);
  inline void add_possible_present_objects(const char* value);
  inline void add_possible_present_objects(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& possible_present_objects() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_possible_present_objects();
  
  // @@protoc_insertion_point(class_scope:androar.Image)
 private:
  inline void set_has_image();
  inline void clear_has_image();
  inline void set_has_localization_features();
  inline void clear_has_localization_features();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::androar::ImageContents* image_;
  ::androar::LocalizationFeatures* localization_features_;
  ::google::protobuf::RepeatedPtrField< ::androar::DetectedObject > detected_objects_;
  ::google::protobuf::RepeatedPtrField< ::std::string> possible_present_objects_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_image_5ffeatures_2eproto();
  friend void protobuf_AssignDesc_image_5ffeatures_2eproto();
  friend void protobuf_ShutdownFile_image_5ffeatures_2eproto();
  
  void InitAsDefaultInstance();
  static Image* default_instance_;
};
// ===================================================================


// ===================================================================

// GPSPosition

// required float latitude = 1;
inline bool GPSPosition::has_latitude() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GPSPosition::set_has_latitude() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GPSPosition::clear_has_latitude() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GPSPosition::clear_latitude() {
  latitude_ = 0;
  clear_has_latitude();
}
inline float GPSPosition::latitude() const {
  return latitude_;
}
inline void GPSPosition::set_latitude(float value) {
  set_has_latitude();
  latitude_ = value;
}

// required float longitude = 2;
inline bool GPSPosition::has_longitude() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GPSPosition::set_has_longitude() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GPSPosition::clear_has_longitude() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GPSPosition::clear_longitude() {
  longitude_ = 0;
  clear_has_longitude();
}
inline float GPSPosition::longitude() const {
  return longitude_;
}
inline void GPSPosition::set_longitude(float value) {
  set_has_longitude();
  longitude_ = value;
}

// -------------------------------------------------------------------

// CompassPosition

// required float angle = 1;
inline bool CompassPosition::has_angle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CompassPosition::set_has_angle() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CompassPosition::clear_has_angle() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CompassPosition::clear_angle() {
  angle_ = 0;
  clear_has_angle();
}
inline float CompassPosition::angle() const {
  return angle_;
}
inline void CompassPosition::set_angle(float value) {
  set_has_angle();
  angle_ = value;
}

// -------------------------------------------------------------------

// LocalizationFeatures

// optional .androar.GPSPosition gps_position = 1;
inline bool LocalizationFeatures::has_gps_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LocalizationFeatures::set_has_gps_position() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LocalizationFeatures::clear_has_gps_position() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LocalizationFeatures::clear_gps_position() {
  if (gps_position_ != NULL) gps_position_->::androar::GPSPosition::Clear();
  clear_has_gps_position();
}
inline const ::androar::GPSPosition& LocalizationFeatures::gps_position() const {
  return gps_position_ != NULL ? *gps_position_ : *default_instance_->gps_position_;
}
inline ::androar::GPSPosition* LocalizationFeatures::mutable_gps_position() {
  set_has_gps_position();
  if (gps_position_ == NULL) gps_position_ = new ::androar::GPSPosition;
  return gps_position_;
}
inline ::androar::GPSPosition* LocalizationFeatures::release_gps_position() {
  clear_has_gps_position();
  ::androar::GPSPosition* temp = gps_position_;
  gps_position_ = NULL;
  return temp;
}

// optional .androar.CompassPosition compass_position = 2;
inline bool LocalizationFeatures::has_compass_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LocalizationFeatures::set_has_compass_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LocalizationFeatures::clear_has_compass_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LocalizationFeatures::clear_compass_position() {
  if (compass_position_ != NULL) compass_position_->::androar::CompassPosition::Clear();
  clear_has_compass_position();
}
inline const ::androar::CompassPosition& LocalizationFeatures::compass_position() const {
  return compass_position_ != NULL ? *compass_position_ : *default_instance_->compass_position_;
}
inline ::androar::CompassPosition* LocalizationFeatures::mutable_compass_position() {
  set_has_compass_position();
  if (compass_position_ == NULL) compass_position_ = new ::androar::CompassPosition;
  return compass_position_;
}
inline ::androar::CompassPosition* LocalizationFeatures::release_compass_position() {
  clear_has_compass_position();
  ::androar::CompassPosition* temp = compass_position_;
  compass_position_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// ObjectBoundingBox

// required int32 bottom = 1;
inline bool ObjectBoundingBox::has_bottom() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ObjectBoundingBox::set_has_bottom() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ObjectBoundingBox::clear_has_bottom() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ObjectBoundingBox::clear_bottom() {
  bottom_ = 0;
  clear_has_bottom();
}
inline ::google::protobuf::int32 ObjectBoundingBox::bottom() const {
  return bottom_;
}
inline void ObjectBoundingBox::set_bottom(::google::protobuf::int32 value) {
  set_has_bottom();
  bottom_ = value;
}

// required int32 top = 2;
inline bool ObjectBoundingBox::has_top() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ObjectBoundingBox::set_has_top() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ObjectBoundingBox::clear_has_top() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ObjectBoundingBox::clear_top() {
  top_ = 0;
  clear_has_top();
}
inline ::google::protobuf::int32 ObjectBoundingBox::top() const {
  return top_;
}
inline void ObjectBoundingBox::set_top(::google::protobuf::int32 value) {
  set_has_top();
  top_ = value;
}

// required int32 left = 3;
inline bool ObjectBoundingBox::has_left() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ObjectBoundingBox::set_has_left() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ObjectBoundingBox::clear_has_left() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ObjectBoundingBox::clear_left() {
  left_ = 0;
  clear_has_left();
}
inline ::google::protobuf::int32 ObjectBoundingBox::left() const {
  return left_;
}
inline void ObjectBoundingBox::set_left(::google::protobuf::int32 value) {
  set_has_left();
  left_ = value;
}

// required int32 right = 4;
inline bool ObjectBoundingBox::has_right() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ObjectBoundingBox::set_has_right() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ObjectBoundingBox::clear_has_right() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ObjectBoundingBox::clear_right() {
  right_ = 0;
  clear_has_right();
}
inline ::google::protobuf::int32 ObjectBoundingBox::right() const {
  return right_;
}
inline void ObjectBoundingBox::set_right(::google::protobuf::int32 value) {
  set_has_right();
  right_ = value;
}

// -------------------------------------------------------------------

// ObjectMetadata

// optional string name = 1;
inline bool ObjectMetadata::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ObjectMetadata::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ObjectMetadata::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ObjectMetadata::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& ObjectMetadata::name() const {
  return *name_;
}
inline void ObjectMetadata::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ObjectMetadata::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ObjectMetadata::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ObjectMetadata::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* ObjectMetadata::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string description = 2;
inline bool ObjectMetadata::has_description() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ObjectMetadata::set_has_description() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ObjectMetadata::clear_has_description() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ObjectMetadata::clear_description() {
  if (description_ != &::google::protobuf::internal::kEmptyString) {
    description_->clear();
  }
  clear_has_description();
}
inline const ::std::string& ObjectMetadata::description() const {
  return *description_;
}
inline void ObjectMetadata::set_description(const ::std::string& value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    description_ = new ::std::string;
  }
  description_->assign(value);
}
inline void ObjectMetadata::set_description(const char* value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    description_ = new ::std::string;
  }
  description_->assign(value);
}
inline void ObjectMetadata::set_description(const char* value, size_t size) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    description_ = new ::std::string;
  }
  description_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ObjectMetadata::mutable_description() {
  set_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    description_ = new ::std::string;
  }
  return description_;
}
inline ::std::string* ObjectMetadata::release_description() {
  clear_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = description_;
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// DetectedObject

// required .androar.DetectedObject.DetectedObjectType object_type = 1;
inline bool DetectedObject::has_object_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetectedObject::set_has_object_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DetectedObject::clear_has_object_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DetectedObject::clear_object_type() {
  object_type_ = 1;
  clear_has_object_type();
}
inline ::androar::DetectedObject_DetectedObjectType DetectedObject::object_type() const {
  return static_cast< ::androar::DetectedObject_DetectedObjectType >(object_type_);
}
inline void DetectedObject::set_object_type(::androar::DetectedObject_DetectedObjectType value) {
  GOOGLE_DCHECK(::androar::DetectedObject_DetectedObjectType_IsValid(value));
  set_has_object_type();
  object_type_ = value;
}

// required .androar.ObjectBoundingBox bounding_box = 2;
inline bool DetectedObject::has_bounding_box() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DetectedObject::set_has_bounding_box() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DetectedObject::clear_has_bounding_box() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DetectedObject::clear_bounding_box() {
  if (bounding_box_ != NULL) bounding_box_->::androar::ObjectBoundingBox::Clear();
  clear_has_bounding_box();
}
inline const ::androar::ObjectBoundingBox& DetectedObject::bounding_box() const {
  return bounding_box_ != NULL ? *bounding_box_ : *default_instance_->bounding_box_;
}
inline ::androar::ObjectBoundingBox* DetectedObject::mutable_bounding_box() {
  set_has_bounding_box();
  if (bounding_box_ == NULL) bounding_box_ = new ::androar::ObjectBoundingBox;
  return bounding_box_;
}
inline ::androar::ObjectBoundingBox* DetectedObject::release_bounding_box() {
  clear_has_bounding_box();
  ::androar::ObjectBoundingBox* temp = bounding_box_;
  bounding_box_ = NULL;
  return temp;
}

// optional .androar.ObjectMetadata metadata = 3;
inline bool DetectedObject::has_metadata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DetectedObject::set_has_metadata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DetectedObject::clear_has_metadata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DetectedObject::clear_metadata() {
  if (metadata_ != NULL) metadata_->::androar::ObjectMetadata::Clear();
  clear_has_metadata();
}
inline const ::androar::ObjectMetadata& DetectedObject::metadata() const {
  return metadata_ != NULL ? *metadata_ : *default_instance_->metadata_;
}
inline ::androar::ObjectMetadata* DetectedObject::mutable_metadata() {
  set_has_metadata();
  if (metadata_ == NULL) metadata_ = new ::androar::ObjectMetadata;
  return metadata_;
}
inline ::androar::ObjectMetadata* DetectedObject::release_metadata() {
  clear_has_metadata();
  ::androar::ObjectMetadata* temp = metadata_;
  metadata_ = NULL;
  return temp;
}

// required string id = 4;
inline bool DetectedObject::has_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DetectedObject::set_has_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DetectedObject::clear_has_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DetectedObject::clear_id() {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    id_->clear();
  }
  clear_has_id();
}
inline const ::std::string& DetectedObject::id() const {
  return *id_;
}
inline void DetectedObject::set_id(const ::std::string& value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void DetectedObject::set_id(const char* value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void DetectedObject::set_id(const char* value, size_t size) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DetectedObject::mutable_id() {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  return id_;
}
inline ::std::string* DetectedObject::release_id() {
  clear_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = id_;
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 distance_to_viewer = 5;
inline bool DetectedObject::has_distance_to_viewer() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DetectedObject::set_has_distance_to_viewer() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DetectedObject::clear_has_distance_to_viewer() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DetectedObject::clear_distance_to_viewer() {
  distance_to_viewer_ = 0;
  clear_has_distance_to_viewer();
}
inline ::google::protobuf::int32 DetectedObject::distance_to_viewer() const {
  return distance_to_viewer_;
}
inline void DetectedObject::set_distance_to_viewer(::google::protobuf::int32 value) {
  set_has_distance_to_viewer();
  distance_to_viewer_ = value;
}

// optional int32 angle_to_viewer = 6;
inline bool DetectedObject::has_angle_to_viewer() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void DetectedObject::set_has_angle_to_viewer() {
  _has_bits_[0] |= 0x00000020u;
}
inline void DetectedObject::clear_has_angle_to_viewer() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void DetectedObject::clear_angle_to_viewer() {
  angle_to_viewer_ = 0;
  clear_has_angle_to_viewer();
}
inline ::google::protobuf::int32 DetectedObject::angle_to_viewer() const {
  return angle_to_viewer_;
}
inline void DetectedObject::set_angle_to_viewer(::google::protobuf::int32 value) {
  set_has_angle_to_viewer();
  angle_to_viewer_ = value;
}

// -------------------------------------------------------------------

// ImageContents

// required string image_hash = 1;
inline bool ImageContents::has_image_hash() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ImageContents::set_has_image_hash() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ImageContents::clear_has_image_hash() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ImageContents::clear_image_hash() {
  if (image_hash_ != &::google::protobuf::internal::kEmptyString) {
    image_hash_->clear();
  }
  clear_has_image_hash();
}
inline const ::std::string& ImageContents::image_hash() const {
  return *image_hash_;
}
inline void ImageContents::set_image_hash(const ::std::string& value) {
  set_has_image_hash();
  if (image_hash_ == &::google::protobuf::internal::kEmptyString) {
    image_hash_ = new ::std::string;
  }
  image_hash_->assign(value);
}
inline void ImageContents::set_image_hash(const char* value) {
  set_has_image_hash();
  if (image_hash_ == &::google::protobuf::internal::kEmptyString) {
    image_hash_ = new ::std::string;
  }
  image_hash_->assign(value);
}
inline void ImageContents::set_image_hash(const char* value, size_t size) {
  set_has_image_hash();
  if (image_hash_ == &::google::protobuf::internal::kEmptyString) {
    image_hash_ = new ::std::string;
  }
  image_hash_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ImageContents::mutable_image_hash() {
  set_has_image_hash();
  if (image_hash_ == &::google::protobuf::internal::kEmptyString) {
    image_hash_ = new ::std::string;
  }
  return image_hash_;
}
inline ::std::string* ImageContents::release_image_hash() {
  clear_has_image_hash();
  if (image_hash_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = image_hash_;
    image_hash_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required bytes image_contents = 2;
inline bool ImageContents::has_image_contents() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ImageContents::set_has_image_contents() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ImageContents::clear_has_image_contents() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ImageContents::clear_image_contents() {
  if (image_contents_ != &::google::protobuf::internal::kEmptyString) {
    image_contents_->clear();
  }
  clear_has_image_contents();
}
inline const ::std::string& ImageContents::image_contents() const {
  return *image_contents_;
}
inline void ImageContents::set_image_contents(const ::std::string& value) {
  set_has_image_contents();
  if (image_contents_ == &::google::protobuf::internal::kEmptyString) {
    image_contents_ = new ::std::string;
  }
  image_contents_->assign(value);
}
inline void ImageContents::set_image_contents(const char* value) {
  set_has_image_contents();
  if (image_contents_ == &::google::protobuf::internal::kEmptyString) {
    image_contents_ = new ::std::string;
  }
  image_contents_->assign(value);
}
inline void ImageContents::set_image_contents(const void* value, size_t size) {
  set_has_image_contents();
  if (image_contents_ == &::google::protobuf::internal::kEmptyString) {
    image_contents_ = new ::std::string;
  }
  image_contents_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ImageContents::mutable_image_contents() {
  set_has_image_contents();
  if (image_contents_ == &::google::protobuf::internal::kEmptyString) {
    image_contents_ = new ::std::string;
  }
  return image_contents_;
}
inline ::std::string* ImageContents::release_image_contents() {
  clear_has_image_contents();
  if (image_contents_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = image_contents_;
    image_contents_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// Image

// required .androar.ImageContents image = 1;
inline bool Image::has_image() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Image::set_has_image() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Image::clear_has_image() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Image::clear_image() {
  if (image_ != NULL) image_->::androar::ImageContents::Clear();
  clear_has_image();
}
inline const ::androar::ImageContents& Image::image() const {
  return image_ != NULL ? *image_ : *default_instance_->image_;
}
inline ::androar::ImageContents* Image::mutable_image() {
  set_has_image();
  if (image_ == NULL) image_ = new ::androar::ImageContents;
  return image_;
}
inline ::androar::ImageContents* Image::release_image() {
  clear_has_image();
  ::androar::ImageContents* temp = image_;
  image_ = NULL;
  return temp;
}

// optional .androar.LocalizationFeatures localization_features = 2;
inline bool Image::has_localization_features() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Image::set_has_localization_features() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Image::clear_has_localization_features() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Image::clear_localization_features() {
  if (localization_features_ != NULL) localization_features_->::androar::LocalizationFeatures::Clear();
  clear_has_localization_features();
}
inline const ::androar::LocalizationFeatures& Image::localization_features() const {
  return localization_features_ != NULL ? *localization_features_ : *default_instance_->localization_features_;
}
inline ::androar::LocalizationFeatures* Image::mutable_localization_features() {
  set_has_localization_features();
  if (localization_features_ == NULL) localization_features_ = new ::androar::LocalizationFeatures;
  return localization_features_;
}
inline ::androar::LocalizationFeatures* Image::release_localization_features() {
  clear_has_localization_features();
  ::androar::LocalizationFeatures* temp = localization_features_;
  localization_features_ = NULL;
  return temp;
}

// repeated .androar.DetectedObject detected_objects = 3;
inline int Image::detected_objects_size() const {
  return detected_objects_.size();
}
inline void Image::clear_detected_objects() {
  detected_objects_.Clear();
}
inline const ::androar::DetectedObject& Image::detected_objects(int index) const {
  return detected_objects_.Get(index);
}
inline ::androar::DetectedObject* Image::mutable_detected_objects(int index) {
  return detected_objects_.Mutable(index);
}
inline ::androar::DetectedObject* Image::add_detected_objects() {
  return detected_objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::androar::DetectedObject >&
Image::detected_objects() const {
  return detected_objects_;
}
inline ::google::protobuf::RepeatedPtrField< ::androar::DetectedObject >*
Image::mutable_detected_objects() {
  return &detected_objects_;
}

// repeated string possible_present_objects = 4;
inline int Image::possible_present_objects_size() const {
  return possible_present_objects_.size();
}
inline void Image::clear_possible_present_objects() {
  possible_present_objects_.Clear();
}
inline const ::std::string& Image::possible_present_objects(int index) const {
  return possible_present_objects_.Get(index);
}
inline ::std::string* Image::mutable_possible_present_objects(int index) {
  return possible_present_objects_.Mutable(index);
}
inline void Image::set_possible_present_objects(int index, const ::std::string& value) {
  possible_present_objects_.Mutable(index)->assign(value);
}
inline void Image::set_possible_present_objects(int index, const char* value) {
  possible_present_objects_.Mutable(index)->assign(value);
}
inline void Image::set_possible_present_objects(int index, const char* value, size_t size) {
  possible_present_objects_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Image::add_possible_present_objects() {
  return possible_present_objects_.Add();
}
inline void Image::add_possible_present_objects(const ::std::string& value) {
  possible_present_objects_.Add()->assign(value);
}
inline void Image::add_possible_present_objects(const char* value) {
  possible_present_objects_.Add()->assign(value);
}
inline void Image::add_possible_present_objects(const char* value, size_t size) {
  possible_present_objects_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Image::possible_present_objects() const {
  return possible_present_objects_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Image::mutable_possible_present_objects() {
  return &possible_present_objects_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace androar

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::androar::DetectedObject_DetectedObjectType>() {
  return ::androar::DetectedObject_DetectedObjectType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_image_5ffeatures_2eproto__INCLUDED
